version: "3"

services:
  cypress:
    image: projectcypress/cypress
    deploy:
      labels:
        - "com.docker.ucp.access.label=/Shared/gateway"
    volumes:
      - cypress-tmp:/home/app/cypress/public/data
    environment:
      - MONGO_PORT_27017_TCP_ADDR=mongodb
      - MONGO_PORT_27017_TCP_PORT=27017
    ports:
      - "3000:3000"
    networks:
      - cypress-net
  mongodb:
    image: mongo:3.4.5
    volumes:
      - /data/db
    networks:
      - cypress-net

networks:
  - cypress-net

volumes:
  cypress-tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
