# Mongoid Configuration for Travis CI
# ===================================
#
development:
  clients:
    default:
      database: cypress_development
      hosts:
        - 127.0.0.1:27017
test:
  clients:
    default:
      database: cypress_test
      hosts:
        - <%= ENV['TEST_DB_HOST'] || '127.0.0.1' %>:27017

production:
  clients:
    default:
      database: cypress_production
      hosts:
        - 127.0.0.1:27017
